apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/kubevirt/kubevirt/releases/download/v1.6.0/kubevirt-operator.yaml
- https://github.com/kubevirt/containerized-data-importer/releases/download/v1.62.0/cdi-operator.yaml
- https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/refs/tags/v4.2.2/deployments/multus-daemonset-thick.yml
patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/volumes/8/hostPath/path
      value: /var/run/netns/
  target:
    kind: Deployment
    name: kube-multus-ds
- patch: |-
    - op: replace
      path: /spec/template/spec/initContainers/0/command
      value:
        - "/usr/src/multus-cni/bin/install_multus"
        - "-d"
        - "/host/opt/cni/bin"
        - "-t"
        - "thick"
  target:
    kind: Deployment
    name: kube-multus-ds
