---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: 1.18.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 24h
  install:
    createNamespace: true
  values:
    crds:
      enabled: true
      keep: false
    prometheus:
      enabled: false
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: cert-manager
  chart:
    spec:
      chart: trust-manager
      version: 0.19.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 24h
  install:
    createNamespace: true
  values:
    crds:
      enabled: true
      keep: false
    secretTargets:
      enabled: true
      authorizedSecrets:
        - tls-trusted-bundle
