---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: intel
  namespace: flux-system
spec:
  interval: 24h
  url: https://intel.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: gpu
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.32.1
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
      interval: 24h
  values:
    manager:
      devices:
        dlb: false
        dsa: false
        fpga: false
        gpu: true
        iaa: false
        qat: false
        sgx: false

