---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubevirt
  namespace: flux-system
spec:
  interval: 24h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/kubevirt
  prune: false
