---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: longhorn-system
  chart:
    spec:
      chart: longhorn
      version: 1.9.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 24h
  values:
    persistence:
      defaultDataLocality: best-effort
      migratable: true
      defaultClassReplicaCount: 2
    preUpgradeChecker:
      jobEnabled: false
    defaultSettings:
      defaultDataPath: /var/mnt/longhorn-storage
      allowCollectingLonghornUsageMetrics: false
    longhornUI:
      replicas: 1
