---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: node-feature-discovery
  namespace: flux-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: kube-system
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.17.3
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
      interval: 24h

