---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 24h
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 24h
  targetNamespace: tailscale
  chart:
    spec:
      chart: tailscale-operator
      version: 1.84.3
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
      interval: 24h
  install:
    createNamespace: true
  values:
    ingressClass:
      enabled: false
