---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      featureGates:
        - LiveMigration
        - NetworkBindingPlugins
    smbios:
      sku: "BeeCloud"
      version: "v0.0.1"
      manufacturer: "KubeVirt"
      product: "beevm"
      family: "bee"
  workloadUpdateStrategy:
    workloadUpdateMethods:
    - LiveMigrate
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
spec:
  config:
    scratchSpaceStorageClass: local-path
    podResourceRequirements:
      requests:
        cpu: "100m"
        memory: "60M"
      limits:
        cpu: "750m"
        memory: "2Gi"
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vm-bridge
  namespace: kubevirt
spec:
  config: '{ "cniVersion": "0.3.1", "name": "vm-bridge", "type": "bridge", "bridge":
    "br50", "disableContainerInterface": false }'
