---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-single-local
parameters:
  backupTargetName: default
  dataEngine: v1
  dataLocality: strict-local
  disableRevisionCounter: "true"
  fromBackup: ""
  fsType: ext4
  migratable: "true"
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  unmapMarkSnapChainRemoved: ignored
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
