---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: client_id
    remoteRef:
      key: "operator-oauth/client_id"
  - secretKey: client_secret
    remoteRef:
      key: "operator-oauth/client_secret"
